# Generated by Django 6.0.5 on 2026-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary_range',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
