# Generated by Django 5.2.14 on 2026-05-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
